### ISSUE TITLE
pal export is broken

### ISSUE THREAD

**Issue by KanedaFr** [42Bastian/sprpck#4]
Hi, 
for some reason, it seems pal export is broken using version 2.3

if I use BMP format -> pal.g is zeroed, pal.br is ok
```
sprpck -s4 -p2 -t6 -u -v gfx/logo_sm.bmp
```
> pal:	DP 000,006,00A,00E,004,045,049,00F,007,07F,008,08F,00A,0AC,0CF,0F0
 
if I use PCX format -> pal is zeroed
```
convert gfx/logo_sm.bmp -depth 4 -compress none gfx/logo_sm.pcx
sprpck -s4 -p2 -t3 gfx/logo_sm.pcx
```
> pal:	DP 000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000
 
I could provide the file if needed, but I have the same result with any image I tried
I also tried with -p0, same result
I looked at your code, but I was unable to find what was wrong.
I only noticed `rgb` var is set twice when using PCX format but probably for a good reason

I built sprpck from source on macOSX, if it could be the reason
It's similar to this issue, which occurred on Win64
https://atariage.com/forums/topic/251579-sprpck-and-palette/

**Comment by KanedaFr** [comment]
the only picture that I found working is bg8bit.bmp

**Comment by 42Bastian** [comment]
Ok, I will check.

**Comment by 42Bastian** [comment]
Do you get the info "PCX:Using palette at the end of file !" ?

**Comment by 42Bastian** [comment]
Ok, found it. The size counting in io.c is somewhat wrong and so sometimes, it assumes that the palette is at the end.

**Comment by 42Bastian** [comment]
Fixed in 2.4

**Comment by KanedaFr** [comment]
Thanks for the fix.
I updated sprpck today and, unfortunately, it is still broken, at least on 4BPP bitmap
You could try with your own bg4bit.bmp => with this latest version, it still lacks green

```
char pal[]={
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
	0x04,0x60,0x08,0x8C,0x84,0x84,0xE8,0x4C,0xE4,0xE4,0x2F,0xFC,0x60,0x00,0x00,0x00};
```

**Comment by 42Bastian** [comment]
Oh puta....
